<a href="https://colab.research.google.com/github/datafreak-adi/practice_ignore/blob/origin/confidence_interval(task_44).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from scipy.stats import t

In [ ]:
import numpy as np

`Question: 1` A company wants to estimate the average time spent by customers on their website per session. They collect a random sample of 100 customers and find that the sample mean time spent is 4.5 minutes with a sample standard deviation of 1.2 minutes. Calculate a 99% confidence interval for the true population mean time spent on the website per session.

In [ ]:
n=100
samp_std=1.2
samp_mean=4.5

alpha=0.01

# NOTE: ppf and cdf have difference between them ; "t.ppf" computes t-value for a specific cumulative point while "t.cdf" computes the cumulative probability for a given t-value.
t_value= t.ppf(1-alpha/2,n-1)

print(t_value)

pop_mean_upper= samp_mean + t_value * (samp_std/n**0.5)
pop_mean_lower= samp_mean - t_value * (samp_std/n**0.5)
print(f"The confidence of population mean lies is range of {pop_mean_lower} to {pop_mean_upper}")

2.6264054572808275
The confidence of population mean lies is range of 4.184831345126301 to 4.815168654873699

`Question 2:` A car manufacturer is interested in estimating the mean gas mileage of their new SUV. A sample of 25 SUVs is taken, and their mean gas mileage is found to be 28.6 miles per gallon with a standard deviation of 2.8 miles per gallon. Calculate a 95% confidence interval for the true mean gas mileage of the SUV.

In [ ]:
n=25
std_sample=2.8
mean_sample=28.6

alpha=0.05

t_critical= t.ppf(1-alpha/2,n-1)

mean_pop= mean_sample + np.array([-1,1])*t_critical * (std_sample/n**0.5)
print(f"The confidence of population mean lies is range of {mean_pop[0]} to {mean_pop[1]}")

The confidence of population mean lies is range of 27.44421680548831 to 29.755783194511693

`Question -3:` Dataset - India temperature dataset.

Data link: https://drive.google.com/file/d/1whb8Rjdk9TBKOwVi8NwZD1Tc8Tdv7iEc/view?usp=share_link

Kaggle Link : (Just take IND data for this question, have to apply filtering). https://www.kaggle.com/datasets/berkeleyearth/climate-change-earth-surface-temperature-data
:
A climate research organization wants to estimate the average temperature of a certain country. They collect temperature data for 2613 days but due to certain limitations, they only have information about the average temperature for 2508 days. The organization assumes that the population follows a normal distribution and wants to estimate the population mean temperature with a 95% confidence interval.

* Standard deviation is assumed as given data standard deviation. z Procedure
* Standard deviation is not given. Apply t Procedure

In [ ]:
import pandas as pd
df=pd.read_csv("ind_temp.csv")

In [ ]:
df.head()

           dt  AverageTemperature  AverageTemperatureUncertainty Country
0  1796-01-01              17.044                          2.044   India
1  1796-02-01              19.193                          1.359   India
2  1796-03-01              22.319                          2.125   India
3  1796-04-01              27.233                          1.510   India
4  1796-05-01              30.035                          1.338   India

In [ ]:
n=50 #(50 sample at a time)
std=[]
sample_test=[]

for i in range (0,200):
  samples= df["AverageTemperature"].dropna().sample(50).values
  sample_test.append(samples.tolist())
  std.append(samples.std())

sample= np.array(sample_test)
sample_mean= sample.mean()
sample_std= np.mean(std)

print(sample_mean)
print(sample_std)

23.8934364
4.290893532632691

In [ ]:
# Calculating t_values and finding pop_mean

n=50
alpha=0.05

t_critical=t.ppf(1-alpha/2, n-1)

range_int= sample_mean + np.array([-1,1])*t_critical * (sample_std/n**0.5)
print(f"The confidence of population mean found using t_procedure lies is range of {range_int[0]} to {range_int[1]}")

The confidence of population mean found using t_procedure lies is range of 22.616477124833196 to 25.058923075166817

In [ ]:
from scipy.stats import norm

In [ ]:
#z_procedure

pop_std= df["AverageTemperature"].dropna().values.std()
alpha=0.05

z_critical = norm.ppf(1-alpha/2)

print(z_critical)

critical_val= sample_mean + np.array([-1,1])*z_critical * (pop_std/n**0.5)
print(f"The confidence of population mean found using z_procedure lies is range of {critical_val[0]} to {critical_val[1]}")

1.959963984540054
The confidence of population mean found using z_procedure lies is range of 22.63890750524557 to 25.036492694754443

`Question 5:` BMW Dataset : https://drive.google.com/file/d/18amVv1WKKHEmwyvVy0RuXp4A6xrGOelc/view?usp=share_link

**Task 1:** The sales manager of a used car company wants to know what is the average selling price of all the used bmw cars. The analyst can collect only a sample of sales of 500 cars in the area. Since this estimate is going to be used by the company to strategize sales of his company, the sample mean should be a good approximation of all the account. What level of confidence is the sales manager going to be satisfied with? What +/- interval number is going to be acceptable?

***The question mentions that a sample of 500 cars is being collected to estimate the average selling price of used BMW cars. If this is the only dataset available for analysis, can we treat this sample as the effective population for this study?***


**When is a sample considered the population?**

If the dataset of 500 cars is the only data available or represents all the used BMW cars being analyzed in that specific area, then this dataset functions as the population for the purpose of this analysis.
In such a case, the use of population formulas (e.g., std(ddof=0)) would be appropriate because there is no additional "larger population" to infer variability from.

**When is it a sample?**

If the dataset of 500 cars is a subset of a much larger group of used BMW cars in the area, then it is a sample. Here, the goal is to generalize findings from the sample to the entire population. In this case, you should apply sample formulas (e.g., std(ddof=1)) because the sample is just an approximation of the population.





**The question states: **

**The analyst can collect only a sample of sales of 500 cars in the area.**

This phrasing implies that the 500 cars are a sample of a larger population of used BMW cars in the area. Therefore:

The dataset of 500 cars is a sample.
To correctly estimate the variability of the population, you should use sample standard deviation (std(ddof=1)).
If the dataset of 500 cars had been explicitly described as exhaustive (i.e., containing all sales in the area), then it would represent the population.

In [ ]:
car_df= pd.read_csv("bmw.csv")

In [ ]:
car_df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

In [ ]:
# For better estimation we consider 95% as best confidence interval


sample_size= 500

# The random_state parameter sets a seed for the random number generator, ensuring reproducibility of random operations;
# any integer (not just 42) can be used as the seed.He Hitchhiker's Guide to the Galaxy by Douglas Adams, where 42 is famously described as the "Answer to the Ultimate Question of Life, the Universe, and Everything."

sample= car_df.sample(sample_size, random_state=42)
sample_mean= car_df["price"].mean()



# ddof=1: It computes the sample standard deviation or variance, dividing by n−1 (where 𝑛 is the number of observations). This is used to estimate the population statistic from a sample, following Bessel's correction.

sample_std= sample["price"].std(ddof=1)
print(sample_std)

alpha= 0.05

z_critical= norm.ppf(1- alpha/2)

confidence_interval= sample_mean + np.array([-1,1])*z_critical * (sample_std/sample_size**0.5)

print(f"The confidence of population mean lies is range of {confidence_interval[0]} to {confidence_interval[1]}")

10979.658607354033
The confidence of population mean lies is range of 21771.01704173385 to 23695.80069317015

**Task 2:** In addition to the price of the car, the manager also wants to now know the average mileage that the car has been driven. But the manager does not have the population standard deviation for the mileage. But the mileage data is available only from the 25 cars that they have sold so far. How do the analyst approach this problem to calculate 95% confidence interval, with only 25 samples?

In [ ]:
car_df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
10776,X3,2016,19000,Automatic,40818,Diesel,150,54.3,2.0
10777,5 Series,2016,14600,Automatic,42947,Diesel,125,60.1,2.0
10778,3 Series,2017,13100,Manual,25468,Petrol,200,42.8,2.0
10779,1 Series,2014,9930,Automatic,45000,Diesel,30,64.2,2.0
10780,X1,2017,15981,Automatic,59432,Diesel,125,57.6,2.0

In [ ]:
sample_size=25

sample= car_df.sample(sample_size, random_state=1)

sample_mean= sample["mileage"].mean()

sample_std= sample["mileage"].std()

alpha= 0.05

t_critical= t.ppf(1- alpha/2, df=24)

confidence_int= sample_mean + np.array([-1,1])* t_critical* sample_std/ (sample_size**0.5)

print(f"The confidence of population mean lies is range of {confidence_int[0]} to {confidence_int[1]}")

The confidence of population mean lies is range of 17957.233417853342 to 32340.12658214666

**Task 3:** The manager is not happy with both the intervals (intervals from task 1 and 2) as the interval for the confidence is very high. The manager now asks the analyst to estimate the average price of the car (similar to task 1) but within a bound of 750 from the mean with 95% condidence level. How many sample does the analyst have to collect to arrive at this confidence interval level?

In [ ]:
# bound of 750 means margin of error is 750

sample=[]
sample_std=[]

for i in range (500):
  samples= car_df["price"].dropna().sample(50)
  sample_std.append(samples.std())


sample= np.array(sample_std)
std= sample.mean()

print(std)
print(std.dtype)

11332.711030137476
float64

In [ ]:
# Now, calculating sample_size

z_critical= norm.ppf(0.975)
margin_of_error= 750.0

sample_size = (z_critical * np.mean(std) / margin_of_error)**2

print(sample_size)

877.0504321985009

**Task 4:** Conversely, after the analyst started collecting the data, after a week he was only able to collect for 420 samples, though he needs 540 samples for Bound of 1,000, if he has to do the analysis now, what is the best interval he can acheive for 95% confidence levels?