<a href="https://colab.research.google.com/github/datafreak-adi/practice_ignore/blob/origin/Feature_Selection(Task_54).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Task` Do feature selection as per metods taught is session 54 on SECOM dataset.

Dataset Link : https://archive.ics.uci.edu/ml/datasets/SECOM

Drive Link : https://docs.google.com/spreadsheets/d/1dFCe1zgokabsiEr6BbWmMJtiMefkrChpJWLiG_0dDkk/edit?usp=share_link

In [176]:
# Write your Code here

### `Solution`

In [177]:
import pandas as pd

data = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQtBXo5cBnDsM2fmfHPm6u72KGUS5FjPHNGMxOfYjA9-CAhmnRpwkIw_rOR3sANJIToiUU__6fbBvig/pub?gid=572763137&single=true&output=csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Columns: 592 entries, Time to Pass/Fail
dtypes: float64(590), int64(1), object(1)
memory usage: 7.1+ MB

In [178]:
data.head()

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,2008-07-19 11:55:00,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,2008-07-19 12:32:00,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2008-07-19 13:17:00,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2008-07-19 14:43:00,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,2008-07-19 15:22:00,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1

In [179]:
import numpy as np

In [180]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Dropping Time column
data.drop('Time', axis=1, inplace=True)

# Filling NaN Values with random
for column in data.columns:

    min_value = data[column].min()
    max_value = data[column].max()

    # Generate random numbers within the range
    random_values = np.random.uniform(min_value, max_value, size=data[column].isnull().sum())

    # Create a Series with the random values
    random_series = pd.Series(random_values, index=data[column][data[column].isnull()].index)

    # Fill NaN values with the random series
    data[column].fillna(random_series, inplace=True)

    # Print
    # print(data[column].isnull().sum())


# data.isnull().sum()

<ipython-input-180-9f328c74a9f7>:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(random_series, inplace=True)

In [181]:
X = data.iloc[: , :-1]
y = data.iloc[: , -1]



# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)


# Initialize and train logistic regression model
log_reg = LogisticRegression(max_iter=10000)  # Increase max_iter if it doesn't converge
log_reg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = log_reg.predict(X_test)

# Calculate and print accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Test accuracy:", accuracy)

(1253, 590)
(314, 590)
Test accuracy: 0.8885350318471338

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## Duplicate Method

**Scenario 1:** If the DataFrame contains *columns with identical values but different names*,
 **duplicate_remove** will consider them duplicates, but **duplicated()** won't.

**Scenario 2:** If the DataFrame contains *columns with the same name but different values*,  **duplicate_remove** won't consider them duplicates, but **duplicated()** will.

In [182]:
# Removing duplicate columns

#### Method 1

def duplicate_remove(df):

  duplicate_col={}
  seen_already={}

  for column in df.columns:

    current_column= df[column]

    # convert column to bytes
    try:

      column_hash_code= current_column.values.tobytes()

    except AttributeError:

      column_has_code= current_column.to_string().encode()

    if column_hash_code in seen_already:

      if seen_already[column_hash_code] in duplicate_col:

         duplicate_col[seen_already[column_hash_code]].append(column)

      else:

         duplicate_col[seen_already[column_hash_code]]= [column]


    else:

        seen_already[column_hash_code]= column


  return duplicate_col

In [183]:
data.shape[1]

591

In [184]:
for value in duplicate_remove(data).values():

   data.drop(columns=value, axis=1, inplace=True)

print( f" Using this duplicate_remove method we are left with {data.shape[1]} columns")

 Using this duplicate_remove method we are left with 479 columns

In [185]:
 # Method 2

## since duplicated method is applicable on rows so we intelligently used it on columns (by transposing it)

data_cp = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQtBXo5cBnDsM2fmfHPm6u72KGUS5FjPHNGMxOfYjA9-CAhmnRpwkIw_rOR3sANJIToiUU__6fbBvig/pub?gid=572763137&single=true&output=csv")
data_test= data_cp.copy()

duplicate_columns= data_cp.columns[data_cp.T.duplicated()]

data_cp.drop(columns=duplicate_columns, axis=1, inplace=True)

data_cp.drop("Time", axis=1, inplace= True)

print( f" Using this duplicated method we manage to delete {data_test.shape[1] - data_cp.shape[1]} number of duplicate columns and left with {data_cp.shape[1]} number of columns")

 Using this duplicated method we manage to delete 105 number of duplicate columns and left with 487 number of columns

In [186]:
data_cp.shape[1]

487

In [187]:
X1 = data_cp.iloc[: , :-1]
y1 = data_cp.iloc[: , -1]



# Split data into training and testing sets
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=42)

print(X1_train.shape)
print(X1_test.shape)

(1253, 486)
(314, 486)

## Variance Threshold

In [188]:
from sklearn.feature_selection import VarianceThreshold as VT

sel= VT(threshold=0.01)

sel.fit(X1_train)

# to get total columns whose variance greater than threshold (jinko hume rakhna hai)

print(f" Number of colums whose variance threshold greater than  {sum(sel.get_support())}")

# to get name of columns whose variance less than threshold

columns_name= X1_train.columns[sel.get_support()]

values= sel.transform(X1_train)


data_vt= pd.DataFrame(values, columns=columns_name)

 Number of colums whose variance threshold greater than  314

## Correlation

##Key takes:


**[1]  np.where()**

Expects a string or boolean value. Therefore we use astype(np.bool_)

**[2] np.triu()**

Return upper triangle

**Parameters:**

**m:** array-like
The input array, usually a 2D matrix.

**k:** int, optional
The diagonal above or below which to zero elements.

*k = 0* (default) corresponds to the main diagonal.

[[1 2 3]

 [0 5 6]

 [0 0 9]]


*k > 0* selects diagonals above the main diagonal.


[[0 2 3]

 [0 0 6]

 [0 0 0]]



*k < 0* includes more of the lower triangle by shifting the boundary below the main diagonal.


**NOTE :**   Use **np.tril()** for lower matrix

In [189]:
corr_matrix = data_vt.corr().abs()
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool_))
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.8)]
data_corr = data_vt.drop(to_drop, axis=1)

# Numbers Of Columns after Variance Threshold Method

print("Number of Columns after Correlation- ", data_corr.shape[1])

Number of Columns after Correlation-  161

## ANOVA

**ANOVA - Approach showed in the session can't be done.** Here every rows of the dataset have some NaN values. ANOVA can't be applied on data having NaN values.

**But**

We can still perform ANOVA analysis by considering each column separately.

ANOVA can be applied to each column individually, comparing the target variable which is Pass/Fail column in our case against the non-missing values in that specific column.

We will drop NaN values of each column before performing the ANOVA

In [190]:
from scipy.stats import f_oneway

column_pvalues=[]

alpha=0.05

data_corr["Pass/Fail"]= data_cp.iloc[:,-1]

for column in data_corr.columns:

  column_data= data_corr[column].dropna()

  anova_results= f_oneway(column_data, data_cp.iloc[:, -1])

  if anova_results.pvalue< alpha:
    # fetching name of columns with p_value less than alpha as for value less than alpha we reject null hypothesis which says(No relation btwn X and Y)
    column_pvalues.append((column, anova_results.pvalue))



column_pvalues.sort(key=lambda x: x[-1])

#The for column, _ in ... syntax is used for unpacking the tuples. column gets assigned the first element (column name) and _ gets assigned the second element (p-value){means throwaway}
# if for _, pvalues ; we would throwaway column numner and get pvalues

selected_column= [column for column, _ in column_pvalues[:100]]

data_anova = data_corr[selected_column+ ["Pass/Fail"]]

print(f" Columns left after annova-test are {data_anova.shape[1]}")

data_anova

 Columns left after annova-test are 101

,0,1,2,3,6,12,14,15,16,18,...,423,426,438,439,442,443,444,460,472,Pass/Fail
0,2951.41,2577.27,2207.8111,1202.4520,108.7689,198.4192,6.3185,395.4402,10.4823,187.9369,...,56.2163,0.5052,27.0386,31.4452,1.2202,0.6551,1.0514,11.4737,146.7090,-1
1,2998.89,2532.66,2189.3556,2363.6412,83.4233,199.4045,6.5451,404.2949,9.8668,189.5377,...,60.8701,1.1005,105.2632,110.0000,1.5597,0.6958,1.0407,28.0078,122.0734,-1
2,3083.49,2536.43,2213.7556,1113.5599,104.1667,197.4467,10.2250,425.1607,10.1609,187.2858,...,63.9218,1.2252,65.0602,65.2045,1.4958,0.8907,0.7449,40.0505,103.1165,1
3,3004.09,2388.74,2223.8000,1503.1248,110.0600,200.0352,4.2144,404.6055,11.0203,189.0149,...,67.8394,1.4902,27.7533,35.7585,0.6535,0.5375,0.7184,40.1977,183.6233,-1
4,3031.79,2479.69,2186.9889,949.2201,103.3322,203.2909,7.5919,401.7990,10.1388,193.1521,...,35.4588,2.1857,60.3093,63.5714,1.5588,0.7507,0.9060,59.3343,113.3371,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248,2995.26,2447.22,2185.1000,1201.0491,105.8489,203.5678,7.7283,408.1332,9.5586,194.0093,...,75.5149,1.8915,75.0000,83.8267,1.7110,0.6436,0.9757,34.4884,174.7690,-1
1249,3020.70,2563.19,2164.2667,711.0258,129.2522,198.8838,7.7410,423.9069,10.1475,188.7363,...,81.7078,0.4674,30.1435,49.2453,1.5185,0.7699,1.1051,44.4877,173.2080,-1
1250,3081.34,2453.78,2175.3445,1147.3421,107.1422,202.4395,5.6030,402.2990,10.5620,191.8775,...,118.5079,0.6087,59.2814,105.6122,1.9690,0.6813,0.8637,32.6200,110.5023,-1
1251,3006.80,2536.87,NaN,NaN,NaN,199.4356,4.0678,416.3835,9.6558,189.7798,...,64.0638,1.1866,60.4743,84.5865,1.7719,0.5351,0.6324,43.2780,149.5860,-1
1252,3038.74,2432.83,2222.0111,1229.4964,105.2711,200.2911,8.3052,421.3147,9.6774,190.6137,...,58.8067,0.5356,47.5771,85.9272,0.9215,0.3119,0.6109,45.0912,150.5016,-1

In [191]:
# check weather we still have null values else we will directly check the accuracy
data_anova.describe()

,0,1,2,3,6,12,14,15,16,18,...,423,426,438,439,442,443,444,460,472,Pass/Fail
count,1248.000000,1250.000000,1239.000000,1239.000000,1239.000000,1251.000000,1250.000000,1250.000000,1250.000000,1250.000000,...,1250.000000,1250.000000,1252.000000,1252.000000,1252.000000,1252.000000,1252.000000,1252.000000,1246.000000,1253.000000
mean,3015.487356,2496.857464,2200.426111,1391.297314,101.062080,199.987094,9.008140,412.923579,9.920873,190.063927,...,77.819903,1.230727,54.293609,70.783503,1.335493,0.630792,0.893605,29.453912,137.494771,-0.861133
std,74.922126,80.782323,29.702387,439.316275,6.129902,3.378515,2.824093,14.926376,2.677292,2.787377,...,32.158066,1.033870,26.586196,38.408856,0.650287,0.145042,0.156642,13.260724,47.302660,0.508582
min,2743.240000,2158.750000,2060.660000,0.000000,82.131100,182.094000,2.249300,333.448600,4.469600,169.177400,...,24.293300,0.363200,0.000000,20.020700,0.097400,0.216900,0.333600,7.953400,11.499700,-1.000000
25%,2965.645000,2453.532500,2181.188900,1081.875800,97.762200,198.162750,7.032600,406.039250,9.569650,188.346175,...,56.050125,0.737000,36.532775,48.031875,0.879000,0.538800,0.803600,20.436950,105.568200,-1.000000
50%,3011.840000,2500.090000,2200.988900,1283.370100,101.492200,199.586700,8.952150,412.300950,9.846200,189.714700,...,70.257050,1.135300,49.090900,65.938200,1.244600,0.640700,0.903300,26.514500,136.898450,-1.000000
75%,3057.787500,2539.492500,2217.666700,1586.947600,104.621150,202.006750,10.925800,419.092575,10.117400,192.171700,...,93.519550,1.537850,66.666700,85.937150,1.577000,0.732300,0.988800,35.727250,168.595775,-1.000000
max,3356.350000,2839.460000,2315.266700,3715.041700,129.252200,272.045100,19.546500,824.927100,102.867700,215.597700,...,424.215200,24.990400,353.164600,657.762100,5.131700,1.085100,1.351100,149.385100,492.771800,1.000000

In [192]:
# Since aur data_annova still has null values we treat them first


# Filling NaN Values with random
for column in data_anova.columns:

    min_value = data_anova[column].min()
    max_value = data_anova[column].max()

    # Generate random numbers within the range
    random_values = np.random.uniform(min_value, max_value,  data_anova[column].isnull().sum())

    # Create a Series with the random values
    random_series = pd.Series(random_values, index= data_anova[column][ data_anova[column].isnull()].index)

    # Fill NaN values with the random series
    data_anova[column].fillna(random_series, inplace=True)

<ipython-input-192-77163d53abab>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_anova[column].fillna(random_series, inplace=True)
<ipython-input-192-77163d53abab>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_anova[column].fillna(random_series, inplace=True)

In [193]:
data_anova.describe()

,0,1,2,3,6,12,14,15,16,18,...,423,426,438,439,442,443,444,460,472,Pass/Fail
count,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,...,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000
mean,3015.792051,2497.162046,2200.302677,1397.044256,101.152688,199.967714,9.010843,413.282179,9.965913,190.062464,...,78.140676,1.285445,54.277299,70.954287,1.337861,0.631031,0.893958,29.475412,138.124459,-0.861133
std,75.273182,81.185032,30.749557,455.116225,6.332573,3.412416,2.823695,17.930342,2.845764,2.806057,...,33.113734,1.521564,26.581847,38.866543,0.655409,0.145230,0.157077,13.277258,48.044894,0.508582
min,2743.240000,2158.750000,2060.660000,0.000000,82.131100,182.094000,2.249300,333.448600,4.469600,169.177400,...,24.293300,0.363200,0.000000,20.020700,0.097400,0.216900,0.333600,7.953400,11.499700,-1.000000
25%,2965.670000,2453.540000,2181.155500,1081.875800,97.762200,198.157300,7.048500,406.041800,9.571600,188.344300,...,56.082000,0.737000,36.486500,48.035600,0.879000,0.538800,0.803600,20.440100,105.725400,-1.000000
50%,3011.840000,2500.130000,2200.988900,1283.436800,101.512200,199.580200,8.956500,412.320400,9.847100,189.715800,...,70.337100,1.136400,49.090900,65.946200,1.244600,0.641200,0.903300,26.557600,137.853400,-1.000000
75%,3058.600000,2539.730000,2217.811100,1588.509000,104.676700,202.006400,10.931200,419.143500,10.123500,192.184500,...,93.788300,1.540300,66.666700,85.967000,1.577000,0.732300,0.988800,35.748700,169.157200,-1.000000
max,3356.350000,2839.460000,2315.266700,3715.041700,129.252200,272.045100,19.546500,824.927100,102.867700,215.597700,...,424.215200,24.990400,353.164600,657.762100,5.131700,1.085100,1.351100,149.385100,492.771800,1.000000

In [194]:
X2 = data_anova.iloc[: , :-1]
y2 = data_anova.iloc[: , -1]



# Split data into training and testing sets
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=42)

print(X2_train.shape)
print(X2_test.shape)


# Initialize and train logistic regression model
log_reg = LogisticRegression(max_iter=10000)  # Increase max_iter if it doesn't converge
log_reg.fit(X2_train, y2_train)

# Make predictions on the test set
y2_pred = log_reg.predict(X2_test)

# Calculate and print accuracy score
accuracy = accuracy_score(y2_test, y2_pred)
print("Test accuracy:", accuracy)

(1002, 100)
(251, 100)
Test accuracy: 0.9243027888446215

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(